SUBROUTINE CBFITPER(PXIN,PYIN,PYINNEW,KNIN,PYINPP,PSIG,PERIOD,PXEXP0,PXEXPDL)
  !
  !     PERIODIC B.C WITH Y(PXIN(1)+PERIOD) = PYIN(1)
  !
  !     PREPARE SECOND DERIVATIVE OF CUBIC SPLINE INTERPOLATION AND NEW
  !     VALUES OF Y AT NODES YNEW FITTED SUCH THAT CHI**2 + TAUS*F''**2
  !     IS MINIMIZED ACCORDING TO HIRSHMAN ET AL, PHYS. PLASMAS 1 (1994) 2280.
  !     TAUS = TAU*SIGMA_K OF PAPER ASSUMING SIGMA_K CONSTANT.
  !
  !     SETTING TAUS=0., ONE FINDS THE USUAL CUBIC SPLINE INT. WITH CHI**2=0
  !     TAUS LARGE => FIT CLOSER TO STRAIGHT LINE (SECOND DERIV.=0)
  !
  !     IF LAPACK ROUTINES NOT AVAILABLE, USE NONSYM.F AND REMOVE "c%nonsym"
  !     (COPIED SOURCE FROM NETLIB.COM)
  !
  !     IF TAUS=0, PYINNEW NOT USED => PYINNEW(1) OR PYINNEW=PYIN IS OK
  !
  !
  USE prec_rkind
  implicit none
  !
  REAL(RKIND), DIMENSION(KNIN) :: PXIN, PYIN, PYINNEW, PYINPP &
       &  ,WHK, WOHK, PSIG
  REAL(RKIND), ALLOCATABLE :: PAMAT(:,:)
  REAL(RKIND), DIMENSION(KNIN) :: FTAUK

  INTEGER :: KTONUM(KNIN), KPM2(KNIN,-2:+2)
  INTEGER INFO2, N, IDOWN, IUP, IRHS
  !
  REAL(RKIND) :: FAKKM2, FAKKM1, FAKK, FAKKP1, FAKKP2, FRHS, fun_FTAUK, ZTAUEFF
  REAL(RKIND) :: PXEXP0, PXEXPDL, ZXEXP0, ZXEXPDL, ZCOFEXP
  REAL(RKIND) :: XTKM1, XTK, XTKP1, XOHKP1, XOHKM1, XHKM1, XHK, XOHKM2, XOHK, XYK, XYKP1, XYKM1, PERIOD
  !
  INTEGER :: ICUBSTD, KNIN, I, J, K, IBAND, IDIAG, &
    &  IDAMAT, IHALF, ISHIFT, IEFF, IKP2, IKP1, IKM1, IKM2, JKM2, JKM1, JK, &
    &  JKP1, JKP2, II
  !
  !%nonsym
!!$      REAL(RKIND) :: ANONSYM(501*9)
!!$      INTEGER :: IPIVOT(501)
  !%nonsym
  CHARACTER*1 ZCHAR
  !
  !     FUNCTIONS FOR MATRIX COEFFICIENTS
  !
  FAKKM2(XTKM1,XOHKM1,XOHKM2) = XTKM1*XOHKM1*XOHKM2
  FAKKM1(XTK,XTKM1,XHKM1,XOHK,XOHKM1,XOHKM2) = XHKM1/6. &
    &  - XOHKM1*(XTK*XOHK+(XTK+XTKM1)*XOHKM1 + XTKM1*XOHKM2)
  FAKK(XTKP1,XTK,XTKM1,XHK,XHKM1,XOHK,XOHKM1) = (XHK+XHKM1)/3. &
    &  +XOHK*XOHK*(XTKP1+XTK) + XOHKM1*(2.*XTK*XOHK+(XTK+XTKM1)*XOHKM1)
  FAKKP1(XTKP1,XTK,XHK,XOHKP1,XOHK,XOHKM1) = XHK/6. &
    &  - XOHK*(XTKP1*XOHKP1+(XTK+XTKP1)*XOHK + XTK*XOHKM1)
  FAKKP2(XTKP1,XOHKP1,XOHK) = XTKP1*XOHKP1*XOHK
  !
  FRHS(XYKP1,XYK,XYKM1,XOHK,XOHKM1) = (XYKP1-XYK)*XOHK &
    &  - (XYK-XYKM1)*XOHKM1
  !
  !     WHEN ONE WANTS AN ARRAY FOR TAU*SIGMA_K**2, THEN ONE SHOULD REPLACE
  !     THE FUNCTION fun_FTAU BY AN ARRAY
  !
  fun_FTAUK(II)= ZTAUEFF*EXP(-ZCOFEXP*(PXIN(II)-ZXEXP0)**2/ZXEXPDL**2)
  ! fun_FTAUK(II) = ZTAUEFF
  !
  !-----------------------------------------------------------------------
  !
  !     0. INITIALIZATION
  !
  ICUBSTD = 0
  IF (PSIG(1) .EQ. 0._RKIND) ICUBSTD = 1
  !
  ZTAUEFF = abs(PSIG(1))
  ZXEXP0 = PXEXP0
  ZXEXPDL = PXEXPDL
  ZCOFEXP = 1.0_RKIND
  IF (ZXEXP0.LT.PXIN(1) .OR. ZXEXP0.GT.PXIN(1)+PERIOD) ZCOFEXP=0.0_RKIND
  !
  !.......................................................................
  !
  !     0.3 PREPARE BAND WIDTH
  !
  IUP   = 4
  IDOWN = 4
  IDAMAT = 13
  IF (ICUBSTD .EQ. 1) THEN
    IUP   = 2
    IDOWN = 2
    IDAMAT = 7
  END IF
  IBAND = IDOWN + IUP + 1
  IDIAG = IBAND
  ALLOCATE(PAMAT(IDAMAT,KNIN))
  !%nonsym
  IDIAG = IBAND
  !%nonsym
  !
  PYINPP = 0.0_RKIND
  PAMAT = 0.0_RKIND
  !
  !     0.2 PRE-COMPUTE H_K AND 1./H_K
  !
  DO K=1,KNIN-1
    WHK(K)  = (PXIN(K+1) - PXIN(K))
    WOHK(K) = 1. / WHK(K)
  END DO
  WHK(KNIN) = PXIN(1) + PERIOD - PXIN(KNIN)
  IF (WHK(KNIN) .EQ. 0.0_RKIND) THEN
    PRINT *,' PXIN(1) + PERIOD - PXIN(KNIN) = 0. IN CBFITPER'
    PRINT *,' DO NOT INCLUDE EXTRA PERIODIC POINT: KNIN .NE. 1', &
      &    ' => CHANGE KNIN TO KNIN-1 ?'
!!$        STOP 'CBFITPER'
    return
  ELSE
    WOHK(KNIN) = 1. / WHK(KNIN)
  ENDIF
  !
  !   0.4 INDEXING OF UNKNOWNS IN ALTERNATIVE UP,DOWN,UP,... WAY IN ORDER
  !   TO KEEP A BAND MATRIX, EVEN IF IT DOUBLES THE BAND-WIDTH:
  !   K -> UNKNOWN_NUMBER:
  !   . KTONUM(K) = INUM WITH INUM=1 FOR K=1 ; =2*(K-1) FOR K IN [2,IHALF];
  !   . INUM=2*(KNIN-K)+3 FOR K IN [IHALF+1,KNIN]; WITH IHALF=KNIN/2 + 1
  !   WARNING: CARE IF KNIN IS ODD
  !
  IHALF = KNIN/2 + 1
  KTONUM(1) = 1
  DO K=2,IHALF
    KTONUM(K) = 2*K - 2
  END DO
  DO K=IHALF+1,KNIN
    KTONUM(K) = 2*(KNIN-K) + 3
  END DO
  !
  !     0.5 DETERMINE NEIGHBOURS: K-2, K-1, .., K+2
  !
  DO ISHIFT=-2,+2
    DO K=1,KNIN
      KPM2(K,ISHIFT) = K + ISHIFT
    END DO
  END DO
  !     PERIODIC ENDS
  KPM2(1,-2)   = KNIN - 1
  KPM2(1,-1)   = KNIN
  KPM2(2,-2)   = KNIN
  KPM2(KNIN-1,+2) = 1
  KPM2(KNIN  ,+1) = 1
  KPM2(KNIN  ,+2) = 2
  !
  !     1. CONSTRUCT MATRIX AND R.H.S
  !     LAPACK SET-UP OF MATRIX:    A(I,J) -> AMAT(I-J+IDIAG, J)
  !
  !.......................................................................
  !     (AS MATRIX SYMMETRIC, COMPUTE ONLY UPPER PART) NOT YET
  !
  DO K=1,KNIN
    IEFF = KTONUM(K) + IDIAG
    IKP2 = KPM2(K,+2)
    IKP1 = KPM2(K,+1)
    IKM1 = KPM2(K,-1)
    IKM2 = KPM2(K,-2)
    !     A(K,K-2)
    JKM2 = KTONUM(IKM2)
    ! PAMAT(IEFF-JKM2,JKM2) =FAKKM2(fun_FTAUK(IKM1),WOHK(IKM1),WOHK(IKM2))
    PAMAT(IEFF-JKM2,JKM2) =FAKKM2(PSIG(IKM1),WOHK(IKM1),WOHK(IKM2))
    !     A(K,K-1)
    JKM1 = KTONUM(IKM1)
    PAMAT(IEFF-JKM1,JKM1) = FAKKM1(PSIG(K),PSIG(IKM1),WHK(IKM1), &
      &    WOHK(K),WOHK(IKM1),WOHK(IKM2))
    !     A(K,K)
    JK = KTONUM(K)
    PAMAT(IEFF-JK,JK) =FAKK(PSIG(IKP1),PSIG(K),PSIG(IKM1),WHK(K), &
      &    WHK(IKM1),WOHK(K),WOHK(IKM1))
    !     A(K,K+1)
    JKP1 = KTONUM(IKP1)
    PAMAT(IEFF-JKP1,JKP1) = FAKKP1(PSIG(IKP1),PSIG(K),WHK(K), &
      &    WOHK(IKP1),WOHK(K),WOHK(IKM1))
    !     A(K,K+2)
    JKP2 = KTONUM(IKP2)
    PAMAT(IEFF-JKP2,JKP2) = FAKKP2(PSIG(IKP1),WOHK(IKP1),WOHK(K))
    !     B(K)
    PYINPP(KTONUM(K)) = FRHS(PYIN(IKP1),PYIN(K),PYIN(IKM1),WOHK(K) &
      &    ,WOHK(IKM1))
    !
  END DO
  !
  !     2. SOLVE SYSTEM
  !
  !     USE INTEGER WORK SPACE FROM KPM2(0) ARRAY FOR IPIVOT,
  !     AS KPM2)K,0) NOT NEEDED NOR USED
  !
  IRHS = 1
  INFO2 = 0
  !   Single precision (using routines in spgbtrf_s.f compiled with -r8 for example)
  !%single      CALL SGBTRF(N,KNIN,IDOWN,IUP,PAMAT,IDAMAT,KPM2(1,0),INFO2)
  !   Double precision (using the lapack libraries from the compiler)
  CALL DGBTRF(KNIN,KNIN,IDOWN,IUP,PAMAT,IDAMAT,KPM2(1,0),INFO2)
  IF (INFO2 .EQ. 0) THEN
    !   single precision with S as first character
    !   double precision with D as first character
    CALL DGBTRS('N',KNIN,IDOWN,IUP,IRHS,PAMAT,IDAMAT,KPM2(1,0),PYINPP, &
      &    KNIN,INFO2)
  ELSE
    PRINT *,' ERROR IN SP/GBTRF: INFO = ',INFO2
    STOP 'INFO'
  ENDIF
  !
  !%nonsym
!!$      DO I=1,IBAND*KNIN
!!$        ANONSYM(I) = 0.0_RKIND
!!$      ENDDO
!!$      DO I=1,KNIN
!!$!     UPPER PART
!!$        DO J=max(1,i),min(i+IUP,n)
!!$          ANONSYM((I-1)*IBAND+J-I+IUP+1) = PAMAT(IDIAG+I-J,J)
!!$        ENDDO
!!$!     LOWER PART
!!$        DO J=max(1,i-IUP),min(i-1,n-1)
!!$          ANONSYM((I-1)*IBAND+J-I+IUP+1) = PAMAT(IDIAG+J-I,I)
!!$        ENDDO
!!$      ENDDO
!!$      CALL NONSYM(ANONSYM,PAMAT,PYINPP,KNIN,IUP,IUP,1.0E-06_RKIND,INFO2)
  !%nonsym
  !
  !     2.2 COPY SOLUTION BACK TO STANDARD NUMBERING, USE PAMAT AS WORK SPACE
  !
  DO K=1,KNIN
    PAMAT(1,K) = PYINPP(KTONUM(K))
  END DO
  DO K=1,KNIN
    PYINPP(K) = PAMAT(1,K)
  END DO
  !
  !     3. COMPUTE NEW VALUES OF Y_K (NON-STANDARD CUBIC SPLINE ONLY)
  !
  IF (ICUBSTD .EQ. 0) THEN
    !
    DO K=1,KNIN
      IKP1 = KPM2(K,+1)
      IKM1 = KPM2(K,-1)
      PYINNEW(K) = PYIN(K) &
        &      - PSIG(K) * ((PYINPP(IKP1)-PYINPP(K))*WOHK(K) &
        &      - (PYINPP(K)-PYINPP(IKM1))*WOHK(IKM1))
    END DO
    !
  ENDIF

  IF (INFO2 .LT. 0) THEN
    PRINT *,' ERROR IN SP/GBTRS: INFO2 = ',INFO2
  ENDIF
  !
  DEALLOCATE(PAMAT)
  !
  RETURN
END SUBROUTINE CBFITPER
