function mkops

op = {'plus','minus','uminus','uplus','times','mtimes','rdivide','ldivide',...
 'mrdivide','mldivide','power','mpower','lt','gt','le','ge','ne','eq','and',...
 'or','not','colon','ctranspose','transpose','horizcat','vertcat',...
 'isnan','isinf','isfinite','isreal','sin','sinh','asin','asinh','cos',...
 'cosh','acos','acosh','tan','tanh','atan','atan2','atanh','sec','sech',...
 'asec','asech','csc','csch','acsc','acsch','cot','coth','acot','acoth',...
 'exp','log','log10','log2','pow2','sqrt','abs','angle','conj','imag','real',...
 'unwrap','fix','floor','ceil','round','mod','rem','sign','min','max'};
for k = 1:length(op)
 fid = fopen(['[-]' op{k} '.m'],'w');
 fprintf(fid,'function y = %s(varargin)\n\n%% PSITBXFUN/%s\n\ny = operator(''%s'',varargin{:});\n',...
  op{k},upper(op{k}),op{k});
 fclose(fid);
end
  
