function params = get_fbt_params_reactor(varargin)

    % --- Fetching FBT parameters ---
  fprintf('\n   --- Fetching FBT input parameters\n')

  % Loading TCABR vacuum vessel, mutuals and Green's functions table
  fprintf('   --- Loading coils and vessel geometry, mutual inductances and resistances\n')
  Coils = load('/home/fmsalvador/matlab/plasma_physics_project/reactor/reactor_coils');
  W     = load('/home/fmsalvador/matlab/plasma_physics_project/reactor/reactor_vacuum_vessel');
  ind = find(isnan(W(:,1))==1);
  static = load('/home/fmsalvador/matlab/plasma_physics_project/reactor/reactor_static'); static.Mvx = static.Mxv.';
  ind0 = find(abs(static.rxx-0.45) == min(abs(static.rxx-0.45)) & abs(static.zxx) == min(abs(static.zxx)));

  % --- Define default parameters ---
  params = struct( ...
      'shot',     0, ...
      'eqtime',   0, ...
      'dt',       20e-3, ...
      'Nb',       7, ...
      'Ip0',      0, ...
      'Ip',       200e3, ...
      'vloop0',   0, ...
      'vloop',    2, ...
      'Bcentr',   -1.1, ...
      'Rcentr',   0.62, ...
      'Rmaxis',   0.615, ...   
      'Zmaxis',   0.0, ... 
      'a',        0.17, ...  
      'kappa',    1.15, ...  
      'deltau',   0.3, ...
      'deltal',   0.9, ...
      'sqrur',    0, ...
      'sqrul',    0.1, ...
      'sqrlr',    0, ...
      'sqrll',    0, ...
      'wp',       2, ...
      'wd',       0, ...
      'Rb',       [ 0.79  0.70  0.60  0.50  0.460  0.70  0.60], ...
      'Zb',       [-0.00  0.15  0.21  0.21 -0.052 -0.13 -0.19], ...
      'Rbfix',    [], ...
      'Zbfix',    [], ...
      'Rxp',      0.475, ...
      'Zxp',      -0.2, ...
      'Rsp',      [], ...
      'Zsp',      [], ...
      'Rsf',      [], ...
      'Zsf',      [], ...
      'neavg',    0, ...
      'Lne',      0, ...
      'imode',    'lmode', ...
      'bcp',      0, ...
      'kinprofs', './', ...
      'zeff',     [], ...
      'ptot',     [], ...
      'te',       [], ...
      'ti',       [], ...
      'ne',       [], ...
      'ni',       [], ...
      'nc',       [], ...
      'nFe',      [], ...
      'fz',       [], ...
      'u_hat',    [], ...
      'omega_hat',[], ...
      'omega_exb',[], ...
      'upol',     [], ...
      'utor',     [], ...
      'd_e',      0, ...
      'd_i',      0, ...
      'p0',       8e3,...
      'p1',       0, ...
      'pprime0',  -0.4,...
      'pprime1',  0,...
      'f1',       0,...
      'ffprime1', 0,...
      'betap',    0.2, ...
      'q0',       1.05, ...
      'li',       0.8, ...
      'i_voltsec', 0, ...
      'volt_sec', 0, ...
      'Niter',    20, ...
      'iter',     0, ...
      'iter_fac', 0.5, ...
      'err',      0.2, ...
      'i_save',    0, ...
      'W',        W, ...
      'limiter',  W(ind(1)+1:end,:), ...
      'Rbb',      [], ...
      'Zbb',      [], ...
      'coils',    Coils(8:end,:), ...
      'Nc_E',     10, ...
      'Nc_F',     4, ...
      'Nc_D',     4, ...
      'plasmaid', 'SN', ...
      't_vv_oh',  0, ...
      'Ip_vv_oh', 0, ...
      'i_ioh',    0, ...
      'Ioh',      0, ...
      'Ioh0',     0, ...
      'Ia0',      zeros(length(Coils(8:end,:)),1), ...
      'Ia',       zeros(length(Coils(8:end,:)),1), ...
      'Ia_vv_oh', zeros(length(Coils(8:end,:)),1), ...
      'i_vessel', 0, ...
      'Iv0',      zeros(160,1), ...
      'Iv',       zeros(160,1), ...
      'Ive',      zeros(160,1), ...
      'jv',       zeros(160,1), ...
      'dRv',      [], ...
      'dZv',      [], ...
      'Mpa0',     static.Mxa(ind0,:), ...
      'Mpv0',     static.Mxv(ind0,:), ...
      'Mvp0',     static.Mvx(:,ind0), ...
      'Lp0',      self_inductance(1.7,0.001,1), ...
      'gridsize', 129, ...
      'gridtype', 'fbt', ...
      'greens',   [], ...
      'rmesh',    [], ...
      'zmesh',    [], ...
      'psic',     [], ...
      'psip',     [], ...
      'psisol',   [], ...
      'brp',      [], ...
      'bzp',      [], ...
      'psioh',    0, ...
      'psiv',     zeros(160,1), ...
      'psi',      [], ...
      'psin',     [], ...
      'jplasma',  [], ...
      'jcur',     [], ...
      'jbs_fac',  1, ...
      'jps_fac',  0, ...
      'mutuals',  [], ...
      'vv',       [], ...
      'fbt',      [], ...
      'itersets', [], ...
      'Prad_H',   0, ...
      'Prad_C',     0, ...
      'Prad_Fe',    0, ...
      'Prad_brem_H',   0, ...
      'Prad_brem_C',     0, ...
      'Prad_brem_Fe',    0, ...
      'Prad',     0, ...
      'Pohm',     0, ...
      'Paux',     0, ...
      'Psol',     0, ...
      'P_LH',     0, ...
      'Pfus',     0, ...
      'Qfus',     0, ...
      'tau_E',    0, ...
      'fce', [], ...
      'fci', [], ...
      'rho_star',   0, ...
      'rho_ce', 0, ...
      'rho_ci', 0);
  
      params.rho_ce = zeros(params.gridsize,1);
      params.rho_ci = zeros(params.gridsize,1);
  
  % --- Overwrite default parameters ---
  for j=1:length(varargin)-1
      if ischar(varargin{j}) && any(strcmpi(fieldnames(params),varargin{j}));
          params.(varargin{j})=varargin{j+1};
      end
  end
  params.f1 = params.Bcentr*params.Rcentr;

  % --- Loading Green's table ---
  fprintf('   --- Loading %ux%u (%s) Green''s functions tables\n',params.gridsize,params.gridsize,params.gridtype)
  eval(['params.greens = load(''/home/fmsalvador/matlab/plasma_physics_project/reactor/greenfunc/green_table_' num2str(params.gridsize) 'x' num2str(params.gridsize) '_fbt.mat'');'])
  params.rmesh = params.greens.r;
  params.zmesh = params.greens.z;
  params.psi = zeros(params.gridsize);
  
  % --- Loading vacuum vessel filaments ---
  [vv,dRv,dZv] = vessel_filaments_reactor;
  params.vv = vv;
  params.dRv = dRv;
  params.dZv = dZv;
  
  % --- Mutuals ---
  params.mutuals = static;

end